config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :users
  root 'homes#index'

  get '/power_rankings/years', to: 'power_rankings#years'
  get '/power_rankings/:year/weeks', to: 'power_rankings#weeks'

  get '/ymwhb/history', to: 'homes#history'
  get 'ymwhb/past_champion', to: 'homes#past_champion'

  patch 'rankings/drag'

  resources :power_rankings, except: [:index] do
    resources :rankings do
      member do
        patch :drag
      end
    end
  end

  # patch 'drag/drag'

  # Sessions
  get '/sign_in', to:'sessions#new', as: 'sign_in'
  post '/sign_in', to: 'sessions#create'
  get '/sign_up', to: 'sessions#sign_up'
  post '/sign_up', to: 'sessions#register'
  delete '/sign_out', to: 'sessions#destroy', as: 'sign_out'

  # Admin Console
  get '/admin_console', to: 'admins#index'
end

app/models/power_ranking.rb
class PowerRanking < ApplicationRecord
  self.inheritance_column = 'type_of_power_ranking'

  belongs_to :user
  has_many :rankings, as: :rankable, dependent: :destroy_async
  mount_uploader :avatar, AvatarUploader

  validates :week, uniqueness: { scope: [:user_id, :year]}

  TYPES = ['Full List', 'Three By Three']

  TYPES_HASH = { 'Full List': 'PowerRanking::FullRanking', 'Three By Three': 'PowerRanking::ThreeByThree' }

  def has_rankings?
    rankings.present?
  end

  def pr_avatar
    avatar.url.present? ? avatar.url : 'burrow.png'
  end
end

app/models/power_ranking/full_ranking.rb
class PowerRanking::FullRanking < PowerRanking
end

app/models/power_ranking/three_by_three.rb
class PowerRanking::ThreeByThree < PowerRanking
end

app/controllers/power_rankings_controller.rb
require 'carrierwave/orm/activerecord'

class PowerRankingsController < ApplicationController
  before_action :set_power_ranking, only: %i[ show edit update destroy ]
  before_action :set_rankings, only: %i[ edit show ]
  before_action :authorize, only: %i[ new edit ]
  before_action :set_last_week_and_year, only: %i[new create]

  def index
    @power_rankings = PowerRanking.all.order(week: :desc)
  end

  def show
    # dont show it unless you're the owner or its published
    unless @power_ranking.user_id == current_user&.id || @power_ranking.published
      respond_to do |format|
        format.html { redirect_to root_url }
        format.json { head :no_content }
      end
    end
  end

  def new
    @power_ranking = PowerRanking.new
  end

  def edit; end

  def create
    @power_ranking = PowerRanking.new(power_ranking_params)

    @power_ranking.user_id = current_user&.id
    avatar_file = params[:power_ranking][:avatar]&.original_filename

    if avatar_file&.match(/\s/)&.present?
      avatar_file = avatar_file.gsub(" ", "_")
    end

    @power_ranking.avatar = avatar_file

    respond_to do |format|
      if @power_ranking.save
        format.html { redirect_to power_ranking_url(@power_ranking), notice: "Power ranking was successfully created." }
        format.json { render :show, status: :created, location: @power_ranking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @power_ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    puts power_ranking_params
    respond_to do |format|
      if @power_ranking.update(power_ranking_params)
        format.html { redirect_to power_ranking_url(@power_ranking), notice: "Power ranking was successfully updated." }
        format.json { render :show, status: :ok, location: @power_ranking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @power_ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @power_ranking.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Power ranking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def years
    power_ranking_years = PowerRanking.where(published: true)
                                      .or(PowerRanking.where(user_id: current_user&.id))
                                      .pluck(:year)
                                      .uniq.sort.reverse

    @power_rankings = power_ranking_years.map do |year|
      PowerRanking.find_by(year: year)
    end
  end

  def weeks
    @year = params[:year]

    @power_rankings = PowerRanking.where(published: true)
                                  .or(PowerRanking.where(user_id: current_user&.id))
                                  .where(year: @year)
                                  .order(:week).reverse

    if @power_rankings.empty?
      respond_to do |format|
        format.html { redirect_to power_rankings_years_url }
        format.json { head :no_content }
      end
    end
  end

  private

    def set_power_ranking
      @power_ranking = PowerRanking.find(params[:id])
    end

    def set_last_week_and_year
      last_weeks_pr = PowerRanking.where(year: Date.today.year).last

      @last_weeks_pr_year = last_weeks_pr.present? ? last_weeks_pr.year : Date.today.year
      @last_weeks_pr_week = last_weeks_pr.present? ? last_weeks_pr&.week + 1 : 1
    end

    def power_ranking_params
      params.require(:power_ranking).permit(:id, :week, :year, :title, :introduction_paragraph, :type, :avatar, :published)
    end

    def set_rankings
      @rankings = @power_ranking.rankings.order(:position)
    end
end

app/helpers/power_rankings_helper.rb
module PowerRankingsHelper
  def background_color(action:)
    ['create', 'new'].include?(action) ? 'bg-white-200' : 'bg-gray-200'
  end

  def weeks_column(index:)
    beginning = [0, 4, 8, 12, 16 ]
    left_middle = [1, 5, 9, 13, 17]
    right_middle = [2, 6, 10, 14]
    last = [3, 7, 11, 15]

    if beginning.include?(index)
      start = 1
      end_col = 2
    elsif left_middle.include?(index)
      start = 2
      end_col = 3
    elsif right_middle.include?(index)
      start = 3
      end_col = 4
    elsif last.include?(index)
      start = 5
      end_col = 6
    end

    "col-start-#{start} col-end-#{end_col}"
  end
end

app/views/power_rankings/_form.html.erb
<%= form_for power_ranking, class: "contents w-full max-w-lg", html: {multipart: true} do |form| %>
  <% if power_ranking.errors.any? %>
    <div id="error_explanation" class="px-3 py-2 mt-3 font-medium text-red-500 rounded-lg bg-red-50">

      <ul>
        <% power_ranking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="flex flex-wrap mt-5 mb-6 -mx-3">
      <div class="w-full px-3 mb-6 md:w-1/2 md:mb-0">
        <%= form.label :week, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= form.number_field :week, class: "appearance-none block w-full #{background_color(action: params['action'])} text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white",
                                     value: power_ranking.persisted? ? power_ranking.week : @last_weeks_pr_week, disabled: ['create', 'new'].exclude?(params['action']) %>
      </div>
    
      <div class="w-full px-3 mb-6 md:w-1/2 md:mb-0">
        <%= form.label :year, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= form.number_field :year, class: "appearance-none block w-full #{background_color(action: params['action'])} text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white",
                                     value: power_ranking.persisted? ? power_ranking.year : @last_weeks_pr_year, disabled: ['create', 'new'].exclude?(params['action']) %>
      </div>

      <div class="w-full px-3 mb-6 md:w-1/2 md:mb-0">
        <%= form.label :title, 'Title (Optional)', class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= form.text_field :title, class: "appearance-none block w-full bg-white-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white",
                                    value: power_ranking.nil? ? "" : power_ranking.title %>
      </div>

      <div class="w-full px-3 mb-6 md:w-1/2 md:mb-0">
        <%= form.label :introduction_paragraph, 'Introduction Paragraph (Optional)', class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= form.text_area :introduction_paragraph, class: "appearance-none block w-full bg-white-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white",
                                                    value: power_ranking.nil? ? "" : power_ranking.introduction_paragraph %>
      </div>

      <div class="w-full px-3 mb-6 md:w-1/2 md:mb-0">
        <%= form.label :type, 'Type', class: 'block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' %>
        <%= form.select :type, options_for_select(PowerRanking::TYPES_HASH, power_ranking.type), class: 'appearance-none block w-full bg-white-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white' %>
      </div>

      <div class="w-full px-3 mb-6 md:w-1/2 md:mb-0">
        <%= form.label :avatar, 'Main Image (Optional)', class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= form.file_field :avatar, class: 'appearance-none block w-full bg-white-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white' %>
      </div>

      <div class="w-full px-3 mb-6 md:w-1/2 md:mb-0">
        <%= form.label :published, 'Publish' %>
        <%= form.check_box :published, class: "w-4 h-4 text-gray-700 bg-gray-200 border-gray-300 focus:ring-blue-500" %>
      </div>
  </div>
  <div>
    <button type="submit" class="grid w-1/4 px-4 py-2 mb-2 text-sm font-medium text-white bg-green-600 border border-transparent rounded-md justify-items-center hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500">
      <% if params[:action] == 'new' %>Save & Add Rankings <% else %>Save<% end %>
    </button>
  </div>
<% end %>

app/views/power_rankings/_full_ranking.html.erb
<% rankings.each do |ranking| %>
    <div class="flex flex-col items-center w-full mt-10 bg-white border rounded-lg shadow-md md:flex-row dark:border-slate-200 dark:bg-white">
      <% if ranking.avatar.url.present? %>
        <%= image_tag(ranking.avatar.url, class: 'object-cover w-full h-full rounded-t-lg md:w-48 md:rounded-none md:rounded-l-lg') %>
      <% end %>
      <div class="flex flex-col justify-between p-4 leading-normal">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-black dark:to-black"><%= ranking.position %>: <%= ranking.team.team_name%></h5>
          <p class="mb-3 font-normal text-black dark:text-black"><%= sanitize(ranking.description) %></p>
      </div>
    </div>
<% end %>

app/views/power_rankings/_full_ranking_form.html.erb
<% dragActions = "dragstart->drag#dragStart dragover->drag#dragOver dragenter->drag#dragEnter drop->drag#drop dragend->drag#dragEnd" %>

<ul>
  <div id="rankings">
  <% rankings.each do |ranking| %>
      <%= content_tag(:div, class: 'bi bi-grip-vertical draggable', draggable: true, data: {
        controller: "drag",
        action: dragActions,
        resource_id: ranking.id,
        url: "/rankings/drag",
        parent: "rankings",
      }) do %>
      <div id="<%= dom_id ranking %>">
        <li class="flex mb-6 border-b border-yellow-500 h-fit">
          <div class="w-full mr-10">
            <% if ranking.avatar.present? %>
            <%= image_tag ranking.avatar.url,
                class: 'object-fill mb-2' %>
              <% end %>
              <div class="flex space-x-2">
                <%= button_to "Delete", "/power_rankings/#{power_ranking.id}/rankings/#{ranking.id}", method: :delete, class: "mb-3 bg-red-600 hover:bg-red-700 text-black-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                <%= link_to "Edit", edit_power_ranking_ranking_path(power_ranking.id, ranking.id), method: :get, class: "bg-yellow-300 hover:bg-yellow-700 mb-3 text-black-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
              </div>
          </div>
          <div>
            <h2 class="mb-3 text-lg font-bold"><%= ranking.position %>: <%= ranking.team.team_name %></h2>
            <p class="break-all">
              <%= sanitize(ranking.description) %>
            </p>
          </div>
        </li>
      </div>
    <% end %>
  <% end %>
</div>
</ul>

app/views/power_rankings/_power_ranking.html.erb
<div id="<%= dom_id power_ranking %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Week:</strong>
    <%= power_ranking.week %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Year:</strong>
    <%= power_ranking.year %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this power ranking", power_ranking, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this power ranking', edit_power_ranking_path(power_ranking), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/power_rankings/_three_by_three.html.erb
<h2 class="text-xl font-bold text-green-600 border-b border-green-600" >Top 3</h2>
<% rankings.first(3).each do |ranking| %>
    <div class="flex flex-col items-center w-full mt-10 bg-white border rounded-lg shadow-md md:flex-row dark:border-slate-200 dark:bg-white">
      <% if ranking.avatar.url.present? %>
        <%= image_tag(ranking.avatar.url, class: 'object-cover w-full h-full rounded-t-lg md:w-48 md:rounded-none md:rounded-l-lg') %>
      <% end %>
      <div class="flex flex-col justify-between p-4 leading-normal">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-black dark:to-black"><%= ranking.team.team_name%></h5>
          <p class="mb-3 font-normal text-black dark:text-black"><%= sanitize(ranking.description) %></p>
      </div>
    </div>
<% end %>
<h2 class="pt-5 text-xl font-bold text-red-600 border-b border-red-600" >Bottom 3</h2>
<% rankings.last(3).each do |ranking| %>
    <div class="flex flex-col items-center w-full mt-10 bg-white border rounded-lg shadow-md md:flex-row dark:border-slate-200 dark:bg-white">
      <% if ranking.avatar.url.present? %>
        <%= image_tag(ranking.avatar.url, class: 'object-cover w-full h-full rounded-t-lg md:w-48 md:rounded-none md:rounded-l-lg') %>
      <% end %>
      <div class="flex flex-col justify-between p-4 leading-normal">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-black dark:to-black"><%= ranking.team.team_name%></h5>
          <p class="mb-3 font-normal text-black dark:text-black"><%= sanitize(ranking.description) %></p>
      </div>
    </div>
<% end %>

app/views/power_rankings/_three_by_three_form.html.erb
<% dragActions = "dragstart->drag#dragStart dragover->drag#dragOver dragenter->drag#dragEnter drop->drag#drop dragend->drag#dragEnd" %>

<h2 class="py-5 text-xl font-bold" >Top 3</h2>
<ul>
  <div id="rankings">
  <% rankings.first(3).each do |ranking| %>
      <%= content_tag(:div, class: 'bi bi-grip-vertical draggable', draggable: true, data: {
        controller: "drag",
        action: dragActions,
        resource_id: ranking.id,
        url: "/rankings/drag",
        parent: "rankings",
      }) do %>
      <div id="<%= dom_id ranking %>">
        <li class="flex mb-6 border-b border-yellow-500 h-fit">
          <div class="w-full mr-10">
            <% if ranking.avatar.present? %>
            <%= image_tag ranking.avatar.url,
                class: 'object-fill mb-2' %>
              <% end %>
              <div class="flex space-x-2">
                <%= button_to "Delete", "/power_rankings/#{power_ranking.id}/rankings/#{ranking.id}", method: :delete, class: "mb-3 bg-red-600 hover:bg-red-700 text-black-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                <%= link_to "Edit", edit_power_ranking_ranking_path(power_ranking.id, ranking.id), method: :get, class: "bg-yellow-300 hover:bg-yellow-700 mb-3 text-black-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
              </div>
          </div>
          <div>
            <h2 class="mb-3 text-lg font-bold"><%= ranking.team.team_name %></h2>
            <p class="break-all">
              <%= sanitize(ranking.description) %>
            </p>
          </div>
        </li>
      </div>
    <% end %>
  <% end %>
</div>
</ul>

<h2 class="text-xl font-bold" >Bottom 3</h2>
<ul>
  <div id="rankings">
  <% rankings.last(3).each do |ranking| %>
      <%= content_tag(:div, class: 'bi bi-grip-vertical draggable', draggable: true, data: {
        controller: "drag",
        action: dragActions,
        resource_id: ranking.id,
        url: "/rankings/drag",
        parent: "rankings",
      }) do %>
      <div id="<%= dom_id ranking %>">
        <li class="flex mb-6 border-b border-yellow-500 h-fit">
          <div class="w-full mr-10">
            <% if ranking.avatar.present? %>
            <%= image_tag ranking.avatar.url,
                class: 'object-fill mb-2' %>
              <% end %>
              <div class="flex space-x-2">
                <%= button_to "Delete", "/power_rankings/#{power_ranking.id}/rankings/#{ranking.id}", method: :delete, class: "mb-3 bg-red-600 hover:bg-red-700 text-black-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                <%= link_to "Edit", edit_power_ranking_ranking_path(power_ranking.id, ranking.id), method: :get, class: "bg-yellow-300 hover:bg-yellow-700 mb-3 text-black-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
              </div>
          </div>
          <div>
            <h2 class="mb-3 text-lg font-bold"><%= ranking.team.team_name %></h2>
            <p class="break-all">
              <%= sanitize(ranking.description) %>
            </p>
          </div>
        </li>
      </div>
    <% end %>
  <% end %>
</div>
</ul>

app/views/power_rankings/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">Editing Week <%= @power_ranking.week %> Power Ranking</h1>

  <%= render "form", power_ranking: @power_ranking %>


  <% unless @power_ranking.type == 'PowerRanking::ThreeByThree' && @rankings.length >= 6 %>
    <%= link_to 'Add New Ranking', new_power_ranking_ranking_path(@power_ranking), class: "mb-5 rounded-lg py-3 px-5 bg-yellow-300 hover:bg-yellow-700 inline-block font-medium" %>
  <% end %>
  <%= link_to "View Power Ranking", power_ranking_path, class: "mb-5 rounded-lg py-3 px-5 bg-blue-300 hover:bg-blue-700 inline-block font-medium" %>



  <div class="w-full mx-auto ">
    <div class="pb-2 mb-6 border-b-2">
      <h2 class="text-xl font-bold">
        Rankings
      </h2>
      <p class="text-gray-700">(drag and drop to reorder rankings)</p>
    </div>

    <% if @power_ranking.type == 'PowerRanking::FullRanking' %>
      <%= render "full_ranking_form", rankings: @rankings, power_ranking: @power_ranking %>
    <% else %>
      <%= render "three_by_three_form", rankings: @rankings, power_ranking: @power_ranking %>
    <% end %>

  </div>
</div>

app/views/power_rankings/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Power rankings</h1>
  </div>

  <div id="power_rankings" class="min-w-full">
    <%= render @power_rankings %>
  </div>
</div>

app/views/power_rankings/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-serif text-4xl mb-2">New Power Ranking</h1>

  <%= render "form", power_ranking: @power_ranking %>
</div>

app/views/power_rankings/show.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice">
      <%= notice %> 
    </p>
  <% end %>
  <h1 class="pb-2 mb-6 text-xl font-bold border-b-2">
    Week <%= @power_ranking.week %> Power Rankings, <%= @power_ranking.year %>
  </h1>

  <% if @current_user.present? %>
  <% if %w[super_admin].include?(@current_user.role) || @power_ranking.user_id == @current_user&.id %>
    <div class="items-center mb-2">
      <%= link_to 'Add/Edit Power Ranking', edit_power_ranking_path(@power_ranking), class: "py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500" %>
      <div class="inline-block ml-2">
        <%= button_to 'Delete this PR', power_ranking_path(@power_ranking), method: :delete, class: "py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
      </div>
    </div>
  <% end %>
  <% end %>

  <div class="mb-5 border-b border-yellow-500">
    <div class="flex justify-center pb-10 m-auto bg-transparent w-100">
        <h1 class="font-serif text-3xl text-black sm:text-1xl"><%= @power_ranking.title %></h1>
    </div>

    <div class="flex justify-center m-auto">
      <% if @power_ranking.avatar.url.present? %>
        <%= image_tag(@power_ranking.avatar.url, class: 'object-contain') %>
      <% end %>
    </div>
    <div class="flex flex-col justify-between p-4 leading-normal">
      <p class="mb-3 font-normal text-black dark:text-black"><%= @power_ranking.introduction_paragraph %></p>
    </div>
  </div>

  <div class="grid w-full grid-cols-1 mb-10 rounded-r-md">
    <% if @power_ranking.type == 'PowerRanking::FullRanking' %>
      <%= render "full_ranking", rankings: @rankings %>
    <% else %>
      <%= render "three_by_three", rankings: @rankings %>
    <% end %>
  </div>
</div>

app/views/power_rankings/weeks.html.erb
<div class="w-screen h-screen">
  <div class="grid grid-cols-2 mb-5 border-b border-yellow-500">
    <div class="col-span-2 m-auto bg-transparent justify-items-center w-100">
        <h1 class="font-mono text-4xl text-gray-700 sm:text-1xl mt"><%= @power_rankings.first.year %> Power Rankings</h1>
    </div>
  </div>
  
  <div class="grid grid-cols-1 space-y-10 lg:grid-cols-4 md:grid-cols-4 rounded-r-md">
    <% @power_rankings.each_with_index do |pr, index| %>
    <a href="<%= power_ranking_path(pr.id) %>" class="<%= weeks_column(index: index) %> relative w-full h-80 md:m-auto">
      <%= image_tag(pr.pr_avatar, class: 'absolute md:rounded-xl opacity-80 object-cover w-full h-80 md:m-auto') %>
      <div class="absolute -bottom-10 left-5 md:border-none">
        <h2 class="font-bold border-b-black">Week: <%= pr.week %></h2>
      </div>
    </a>
    <% end %>
  </div>
</div>

app/views/power_rankings/years.html.erb
<div class="w-screen h-screen">
  <div class="grid grid-cols-2 mb-5 border-b border-yellow-500">
    <div class="col-span-2 m-auto bg-transparent justify-items-center w-100">
      <h1 class="font-mono text-4xl text-gray-700 sm:text-1xl mt">Power Rankings</h1>
    </div>
  </div>

  <div class="grid grid-cols-1 gap-4 m-auto md:grid-cols-4 rounded-r-md">
    <% @power_rankings.each_with_index do |pr, index| %>
    <a href="/power_rankings/<%= pr.year %>/weeks" class="<%= weeks_column(index: index) %> relative w-full h-80 md:m-auto mb-10">
      <%= image_tag(pr.pr_avatar, class: 'absolute md:rounded-xl opacity-80 object-cover w-full h-80 md:m-auto') %>
      <div class="absolute -bottom-10 left-5 md:border-none">
        <h2 class="font-bold border-b-black"><%= pr.year %></h2>
      </div>
    </a>
    <% end %>
  </div>
</div>