config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :users
  root 'homes#index'

  get '/power_rankings/years', to: 'power_rankings#years'
  get '/power_rankings/:year/weeks', to: 'power_rankings#weeks'

  get '/ymwhb/history', to: 'homes#history'
  get 'ymwhb/past_champion', to: 'homes#past_champion'

  patch 'rankings/drag'

  resources :power_rankings, except: [:index] do
    resources :rankings do
      member do
        patch :drag
      end
    end
  end

  # patch 'drag/drag'

  # Sessions
  get '/sign_in', to:'sessions#new', as: 'sign_in'
  post '/sign_in', to: 'sessions#create'
  get '/sign_up', to: 'sessions#sign_up'
  post '/sign_up', to: 'sessions#register'
  delete '/sign_out', to: 'sessions#destroy', as: 'sign_out'

  # Admin Console
  get '/admin_console', to: 'admins#index'
end

app/models/ranking.rb
class Ranking < ApplicationRecord
  belongs_to :rankable, polymorphic: true
  acts_as_list scope: [:rankable_id]
  belongs_to :user
  belongs_to :team
  mount_uploader :avatar, AvatarUploader

  validates :team_id, uniqueness: { scope: [:rankable_id, :rankable_type]}
end

app/controllers/rankings_controller.rb
require 'carrierwave/orm/activerecord'

class RankingsController < ApplicationController
  before_action :set_ranking, only: %i[ show edit update destroy ]
  before_action :set_team_name, only: %i[ create ]
  before_action :set_power_ranking, except: :drag
  before_action :set_teams, only: %i[new create]

  # GET /rankings or /rankings.json
  def index
    @rankings = Ranking.all
  end

  # GET /rankings/1 or /rankings/1.json
  def show
  end

  # GET /rankings/new
  def new
    @ranking = Ranking.new
  end

  # GET /rankings/1/edit
  def edit
  end

  # POST /rankings or /rankings.json
  def create
    @ranking = Ranking.new(ranking_params)
    @ranking.user = current_user
    @ranking.rankable = @power_ranking
    @ranking.position = @power_ranking.rankings.length + 1
    @ranking.rank_number = @ranking.position
    avatar_file = params[:ranking][:avatar]&.original_filename

    if avatar_file.present?
      if avatar_file.match(/\s/).present?
        avatar_file = avatar_file.gsub(" ", "_")
      end
    end

    @ranking.avatar = avatar_file 

    respond_to do |format|
      if @ranking.save
        format.html { redirect_to edit_power_ranking_url(@power_ranking), notice: "Ranking was successfully created." }
        format.json { render :show, status: :created, location: @ranking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rankings/1 or /rankings/1.json
  def update
    respond_to do |format|
      if @ranking.update(ranking_params)
        format.html { redirect_to edit_power_ranking_url(@power_ranking), notice: "Ranking was successfully updated." }
        format.json { render :show, status: :ok, location: @ranking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rankings/1 or /rankings/1.json
  def destroy
    @ranking.destroy

    respond_to do |format|
      format.html { redirect_to edit_power_ranking_path(@power_ranking), notice: "Ranking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def drag
    ranking = Ranking.find_by(id: params[:ranking][:id])

    new_position = params[:ranking][:position].to_i + 1

    ranking.insert_at(new_position)

    head :ok
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ranking
      @ranking = Ranking.find_by(id: params[:id])
    end

    def set_team_name
      @team_name = Team.find_by(id: ranking_params[:team_id]).team_name
    end

    def set_teams
      @teams = Team.all.order(team_name: :desc)
    end

    # Only allow a list of trusted parameters through.
    def ranking_params
      params.require(:ranking).permit(:id, :rank_number, :description, :team_id, :position, :power_ranking_id, :avatar)
    end

    def set_power_ranking
      @power_ranking = PowerRanking.find_by(id: params['power_ranking_id'])
    end
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/rankings/_form.html.erb
<%= form_for [@power_ranking, @ranking] do |form| %>
  <% if ranking.errors.any? %>
    <div id="error_explanation" class="px-3 py-2 mt-3 font-medium text-red-500 rounded-lg bg-red-50">

      <ul>
        <% ranking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% unless params[:action] == 'edit' %>
  <div class="my-5">
      <%= form.label :team_name %>
      <%= form.collection_select :team_id, teams, :id, :team_name %>
  </div>
  <% end %>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, class: "block p-2.5 w-full text-black text-sm bg-white-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-white-700 dark:border-gray-600 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="my-5">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, class: "ml-0 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    <%= link_to "Back to Power Ranking", edit_power_ranking_path(@power_ranking.id), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/rankings/_ranking.html.erb
<div id="<%= dom_id ranking %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Rank number:</strong>
    <%= ranking.rank_number %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= ranking.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Team:</strong>
    <%= ranking.team_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Position:</strong>
    <%= ranking.position %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this ranking", ranking, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this ranking', edit_ranking_path(ranking), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/rankings/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">Editing <%= @ranking.team.team_name %>'s Ranking</h1>
  <h2 class="mt-1 text-2xl font-bold">Week <%= @power_ranking.week %>, <%= @power_ranking.year %></h2>
  <p class="text-sm"> Ranking: <%= @ranking.position %></p>

  <%= render "form", ranking: @ranking %>
</div>

app/views/rankings/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Rankings</h1>
    <%= link_to 'New ranking', new_ranking_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="rankings" class="min-w-full">
    <%= render @rankings %>
  </div>
</div>

app/views/rankings/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">New Ranking</h1>
   
    <%= render "form", ranking: @ranking, teams: @teams %>
</div>

app/views/rankings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @ranking %>

    <%= link_to 'Edit this ranking', edit_ranking_path(@ranking), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this ranking', ranking_path(@ranking), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to rankings', rankings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>