config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :users
  root 'homes#index'

  get '/power_rankings/years', to: 'power_rankings#years'
  get '/power_rankings/:year/weeks', to: 'power_rankings#weeks'

  get '/ymwhb/history', to: 'homes#history'
  get 'ymwhb/past_champion', to: 'homes#past_champion'

  patch 'rankings/drag'

  resources :power_rankings, except: [:index] do
    resources :rankings do
      member do
        patch :drag
      end
    end
  end

  # patch 'drag/drag'

  # Sessions
  get '/sign_in', to:'sessions#new', as: 'sign_in'
  post '/sign_in', to: 'sessions#create'
  get '/sign_up', to: 'sessions#sign_up'
  post '/sign_up', to: 'sessions#register'
  delete '/sign_out', to: 'sessions#destroy', as: 'sign_out'

  # Admin Console
  get '/admin_console', to: 'admins#index'
end

app/views/admins/index.html.erb
<div class="p-10">
    <ul class="rounded grid grid-cols-4 sm:grid-cols-1 md:grid-cols-4 lg:grid-cols-4 xl:grid-cols-4 gap-5">
        <li class="rounded shadow-lg mb-3">
          <%= link_to new_power_ranking_path, class: "rounded-md py-3 px-5 text-sm text-black block font-medium" do %>
            <div class="aspect-square">
              <%= image_tag('logo.png', size: "200x300", class: 'w-full') %>
            </div>
            <div class="text-xl px-6 py-4">New Power Ranking</div>
          <% end %>
        </li>
        <% if %w[super_admin].include?(@current_user.role) %>
        <li class="rounded shadow-lg mb-3">
          <%= link_to users_path, method: :get, class: "rounded-md py-3 px-5 text-sm text-black block font-medium" do %>
            <div class="aspect-square">
              <%= image_tag('burrow.png', size: "200x300", class: 'w-full') %>
            </div>
            <div class="text-xl px-6 py-4">Users</div>
          <% end %>
        </li>
        <% end %>
    </ul>
  </div>